/*
 * Exercise5.c
 *
 *  Created on: 13 Sep 2024
 *      Author: HOANG ANH
 */

#include "Exercise5.h"

void EX5_Init5(void){

		GPIO_InitTypeDef GPIO_InitStruct = {0};

		/* GPIO Ports Clock Enable */
			__HAL_RCC_GPIOA_CLK_ENABLE();
			__HAL_RCC_GPIOB_CLK_ENABLE();

		/*Configure GPIO pins*/
		GPIO_InitStruct.Pin = SEG_0|SEG_1|SEG_2|SEG_3|
							SEG_4|SEG_5|SEG_6|SEG_7|SEG_8|SEG_9;
		GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
		GPIO_InitStruct.Pull = GPIO_NOPULL;
		GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
		HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

		GPIO_InitStruct.Pin = LED_1|LED_2|LED_3|
							LED_4|LED_5|LED_6|
							LED_7 |LED_8|LED_9|
							LED_10|LED_11|LED_12|SEG_10|SEG_11|SEG_12|SEG_13;
	    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
	    GPIO_InitStruct.Pull = GPIO_NOPULL;
	    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
	    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

}

void dis7seg_G1(int num1) {
  switch (num1) {
  case 0:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
		  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
		  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
	  break;
  case 1:
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
 	  break;
  case 2:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
	  break;
  case 3:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
	  break;
  case 4:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
	  break;
  case 5:
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
 	  break;
  case 6:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
	  break;
  case 7:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
  	  break;
  case 8:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
  	  break;
  case 9:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
  	  break;
  }
}

void dis7seg_G2(int num2) {
  switch (num2) {
  case 0:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
		  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
		  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
	  break;
  case 1:
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
 	  break;
  case 2:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
	  break;
  case 3:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
	  break;
  case 4:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
	  break;
  case 5:
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
 	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
 	  break;
  case 6:
	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_SET);
	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
	  break;
  case 7:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
  	  break;
  case 8:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
  	  break;
  case 9:
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
  	  	  HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
  	  break;
  }
}
void Ex_5(int state)
{
	   switch (state) {
	        case 4:
	        	//LED-RED 5s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_SET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET); //D4
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		 	  	HAL_Delay(1000);

	        	//LED-RED 4s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_SET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		 	  	HAL_Delay(1000);

	        	//LED-RED 3s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_SET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
			  	HAL_Delay(1000);
			  	break;

	        case 3:
	        	//LED-RED 2s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_SET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_SET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
			  	HAL_Delay(1000);

				//LED-RED 1s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_SET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_SET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_SET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_SET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_RESET); //D4
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
		 	  	HAL_Delay(1000);
		 	  	break;

	        case 2:
	        	//LED-GREEN 3s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
			  	HAL_Delay(1000);

	        	//LED-GREEN 2s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
			  	HAL_Delay(1000);

	        	//LED-GREEN 1s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_SET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_RESET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET); //D4
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		 	  	HAL_Delay(1000);
		 	  	break;

	        case 1:
				//LED-YELLOW 2s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET); //D4
			  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
			  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
			  	HAL_Delay(1000);

				//LED-YELLOW 1s
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET); //X1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET); //V1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, GPIO_PIN_RESET); //D1
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET); //X2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_RESET); //V2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET); //D2
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, GPIO_PIN_RESET); //X3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, GPIO_PIN_SET); //V3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, GPIO_PIN_RESET); //D3
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_RESET); //X4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, GPIO_PIN_RESET); //V4
				HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, GPIO_PIN_SET); //D4
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		 	  	HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
		 	  	HAL_Delay(1000);
		 	  	break;
	   }
}

